language: node_js
node_js:
  - "iojs"
before_install:
  - "npm install mocha -g"
  - curl http://haxe.org/website-content/downloads/3.2.0/downloads/haxe-3.2.0-linux64.tar.gz > haxe.tar.gz
  - tar -xzf haxe.tar.gz -C ~
  - export HAXE_STD_PATH=~/haxe-3.2.0/std
  - export HAXE_HOME=~/haxe-3.2.0
  - chmod +x ./build.sh
  - chmod +x ~/haxe-3.2.0/haxe
script: ./build.sh